micronaut:
  application:
    name: micronautRestfulSample
  server:
    port: 8080
datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    dialect: H2
jpa:
  default:
    packages-to-scan:
    - com.rest.micronaut
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true